version: "3.9"

services:
  db:
    image: postgres:16
    container_name: optsite_db
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - optnet

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: optsite_php
    working_dir: /var/www/web
    volumes:
      - ./:/var/www
    networks:
      - optnet

  web:
    image: nginx:stable
    container_name: optsite_web
    depends_on:
      - php
      - db
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    networks:
      - optnet

networks:
  optnet:
    driver: bridge

volumes:
  db_data:
